config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    # passwords: 'users/passwords'
  }

  devise_scope :users do
    get '/users', to: redirect("/users/sign_up")
  end



  resources :blogs do
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'see' => 'blogs#see'
      get 'look' => 'blogs#look'
      get 'saw' => 'blogs#saw'
      get 'watch' => 'blogs#watch'
      get 'seeing' => 'blogs#seeing'
      get 'looking' => 'blogs#looking'
      get 'check' => "blogs#check"
      get "try" => "blogs#try"
      get "gaze" => "blogs#gaze"
      get "info" => "blogs#info"
      get "precautions" => "blogs#precautions"
    end
  end

  resources :users do
    collection do
      get 'withdraw' => 'users#withdraw'
      get 'follows' => 'users#follows'
      get 'followers' => 'users#followers'
    end
    member do
      get 'show_modal' => 'users#show_modal'
    end
  end


  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:create]

  # resources :users, only: [:show, :edit, :update, :create, :destroy, :show_modal]

  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  patch 'users/update'
  get 'comments/create'
  get 'comments/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'blogs#browse'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get 'top' => 'homes#top'
  get 'browse' => 'blogs#browse'
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :tweets

	mount_uploader :image, ProfileImageUploader

	validates :title, presence: true, length: { maximum: 30 }
	validates :body, presence: true, length: { maximum: 1000 }

  def favorited_by?(user)
     favorites.where(user_id: user.id).exists?
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :authenticate_user!, except: %i[browse]
  before_action :set_target_blog, only: %i[show edit update destroy]

  def index
    @blogs = Blog.page(params[:page]).reverse_order
  end

  def show
    # @comment = Comment.new(blog_id: @blog.id)
    @blog = Blog.includes(:user).find(params[:id])
    @comments = @blog.comments
    @comment = Comment.new
    @tweets = @blog.tweets
    @tweet = Tweet.new
  end

  def new
    @blog = Blog.new(flash[:board])
  end

  def edit

  end

  def update
    @blog.update(blog_params)
    flash[:notice] = "「#{@blog.title}」の感想を更新しました!"
    redirect_to blog_path
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    @blog.image = params[:blog][:image] if params[:blog_image_update_flg].present?

      if @blog.save
        flash[:notice] = "「#{@blog.title}」の感想が投稿されました!"
        redirect_to '/blogs'
      else
        render = 'new'
      end
      

  end

  def destroy
    @blog.delete
    flash[:notice] = "「#{@blog.title}」の感想を削除しました!"
    redirect_to blogs_path
  end

  def browse
  end

  def look
    @tweets = Tweet.where(:action_name => action_name)
    @tweet = Tweet.new
    @blogs = Blog.all.page(params[:page]).per(10)
  end

  def see
    @tweets = Tweet.where(:action_name => action_name)
    @tweet = Tweet.new
    @blogs = Blog.all.page(params[:page]).per(10)
  end

  def saw
    @tweets = Tweet.where(:action_name => action_name)
    @tweet = Tweet.new
    @blogs = Blog.all.page(params[:page]).per(10)
  end

  def watch
    @tweets = Tweet.where(:action_name => action_name)
    @tweet = Tweet.new
    @blogs = Blog.all.page(params[:page]).per(10)
  end

  def seeing
    @tweets = Tweet.where(:action_name => action_name)
    @tweet = Tweet.new
    @blogs = Blog.all.page(params[:page]).per(10)
  end

  def looking
    @tweets = Tweet.where(:action_name => action_name)
    @tweet = Tweet.new
    @blogs = Blog.all.page(params[:page]).per(10)
  end

  def check
    @tweets = Tweet.where(:action_name => action_name)
    @tweet = Tweet.new
    @blogs = Blog.all.page(params[:page]).per(10)
  end

  def try
    @tweets = Tweet.where(:action_name => action_name)
    @tweet = Tweet.new
    @blogs = Blog.all.page(params[:page]).per(10)
  end

  def gaze
    @tweets = Tweet.where(:action_name => action_name)
    @tweet = Tweet.new
    @blogs = Blog.all.page(params[:page]).per(10)
  end

  def info
  end

  def precautions
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :body, :name, :image).merge(user_id: current_user.id)
    end

    def set_target_blog
      @blog = Blog.find(params[:id])
    end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="b-card_box">
	<div class="card">
	  <div class="card-header">
	      <h4><%= @blog.title %></h4>
	  </div>

	  <div class="card-body">
			<div class="left_card">
				<div class="card-image">
					<% if @blog.image.present? %>
						<%= image_tag @blog.image.to_s, :size =>'200x200' %>
					<% end %>
				</div>
			</div>

			<div class="right_card">
				<div class="card_group">
	    		<p class="card-text"><%= simple_format(@blog.body) %></p>
				</div>
			</div>
	  </div>

	  <ul class="card-footer">
	      <%= @blog.user.name %>
				<% if @blog.present? %>
				  <% if @blog.favorited_by?(current_user) %>
						<li class="card-footer">
							<%= link_to blog_favorites_path(@blog), method: :delete do %>
								<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
									<%= @blog.favorites.count %>
							<% end %>
						</li>
							<% else %>
						<li>
							<%= link_to blog_favorites_path(@blog), method: :post do %>
								<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
									<%= @blog.favorites.count %>
							<% end %>
						</li>
				  <% end %>
			<% end %>
		</ul>

	</div>
</div>

app/views/blogs/_btn.html.erb
   <span id="back">
      <a href="#">
        <%= image_tag 'img/arrow.png' %>
      </a>
    </span>

app/views/blogs/_impressions.html.erb
<div class="impressions_button">
	<%= link_to 'スーパー銭湯の共有をしましょう♪', new_blog_path, class: 'btn-border-comment', method: :get %>
</div>

app/views/blogs/_tweet.html.erb
<% if flash[:error_massages] %>
    <div class="alert alert-danger">
        <ul>
            <% flash[:error_massages].each do |massage| %>
                <li><<%= massage %></li>
            <% end %>
        </ul>
    </div>
<% end %>

    <%= render 'shared/error_messages' %>

    <%= form_for @tweet do |f| %>

        <div class="b-tweet__formbox">
            <div class="b-content_box">
                <%= f.text_area :tweet, class: 'form-control', rows: 5 %>
                <small id="content-tip" class="form-text text-muted">
                    コメントを入力してください♪(500文字以内)
                </small>
                <%= f.hidden_field :action_name, :value => controller.action_name %>
            </div>

            <div class="b-push_box2">
                <%= f.submit '投稿！', class: 'decorated-btn2 click-down' %>
            </div>
        </div>

    <% end %>
<% @tweets.each do |tweet| %>
	<div class="b-comment__item">
	  <p><%= simple_format(tweet.tweet) %>
	  <div class="b-comment__bottomLine">
      <span><%= tweet.user.name %></span>
      </div>
    </div>
<% end %>
<%= paginate @blogs %>

app/views/blogs/browse.html.erb
<body>

<%= render 'menu' %>

<%= render 'btn' %>


<div class="main-visual">
  <div id=container-js>
     <div id="theTarget">
        <div class="image1"></div>
        <div class="image2"></div>
        <div class="image3"></div>
        <div class="image4"></div>
        <div class="image5"></div>
    </div>
  </div>
</div>

<div class="container-yu">
  <div class="yunokokoti">
      <span class="yunokokoti-text">
        <h1>♨️〜ようこそ湯のここちへ〜♨️</h1>
      </span>
      <span class="yunokokoti-text2"></p>
            <h3>このサイトは神奈川県にあるスーパー銭湯を紹介するサイトです。<br>
                                                               <br>
            日々仕事等でお疲れの皆さま・・・<br>
            いつもお疲れ様です♪<br>
            スーパー銭湯で優雅で贅沢なひと時を過ごされてはいかがでしょうか？</h3>
      </span>
  </div>
</div>


  <div class="portfolio">
    <div class="container1">
      <h2 class="heading1">♨️〜スーパー銭湯紹介!〜♨️</h2>
      <p class="heading-text">
        <font size="5">日々お仕事を一生懸命働いている皆様へ・・・<br>
        神奈川県で温泉という至福のひと時はいかがでしょうか・・・♨️</font><br>
      </p>

      <div class="spa-images1">
        <div class="pic_frame">
          <%= link_to look_blogs_path do %>
            <div class="portfolio_image1"></div>
          <% end %>
          <p class="portfolio-text">横浜市 竜泉寺の湯</p>
        </div>
        <div class="pic_frame">
          <%= link_to see_blogs_path do %>
            <div class="portfolio_image2"></div>
          <% end %>
          <p class="portfolio-text">海老名市 おふろの王様</p> 
        </div>
        <div class="pic_frame">
          <%= link_to saw_blogs_path do %>
            <div class="portfolio_image3"></div>
          <% end %>
          <p class="portfolio-text">みなとみらい 万葉倶楽部</p>
        </div>
      </div>

      <div class="spa-images2">
        <div class="pic_frame">
          <%= link_to watch_blogs_path do %>
            <div class="portfolio_image4"></div>
          <% end %>
          <p class="portfolio-text">横浜市 満天の湯</p>
        </div>
        <div class="pic_frame">
          <%= link_to seeing_blogs_path do %>
            <div class="portfolio_image5"></div>
          <% end %>
          <p class="portfolio-text">海老名市 OYUGIWA</p> 
        </div>
        <div class="pic_frame">
          <%= link_to looking_blogs_path do %>
            <div class="portfolio_image6"></div>
          <% end %>
          <p class="portfolio-text">厚木市 湯花楽</p>
        </div>
      </div>

      <div class="spa-images3">
        <div class="pic_frame">
          <%= link_to check_blogs_path do %>
            <div class="portfolio_image7"></div>
          <% end %>
          <p class="portfolio-text">座間市 湯快爽快</p>
        </div>
        <div class="pic_frame">
          <%= link_to try_blogs_path do %>
            <div class="portfolio_image8"></div>
          <% end %>
          <p class="portfolio-text">川崎市 湯けむりの庄</p> 
        </div>
        <div class="pic_frame">
          <%= link_to gaze_blogs_path do %>
            <div class="portfolio_image9"></div>
          <% end %>
          <p class="portfolio-text">横浜市 極楽湯</p>
        </div>
      </div>
    </div>
  </div>

        <section class="profile">
             <div class="container2">
               <h2 class="heading2">
                 ♨️〜自己紹介〜♨️
               </h2>
                <p class="heading-text">
                 今回ブログ風紹介サイト『湯のここち』というサイトを制作しました! <br>
                 温泉サイトを制作した理由は、私自身スーパー銭湯が好きで以前からよく通っていました。 <br>
                 現代はストレス社会と言われており、日々ストレスと戦う皆様に少しでも癒しになればと思い制作しました。<br>
                 少しでも皆さまにスーパー銭湯の魅力や素晴らしさを知ってもらえたら嬉しいです♪
               </p>
                 <div class="profile-group clearfix">
                    <div class="left-content">
                     <div class="my-face"></div>
                    </div>
                        <div class="">
                        <h3 class="discription-title">名前</h3>
                        <div class="admin-name">
                          <h2>渡邊 義信</h2>
                        </div>
                        <h3 class="discription-title">マイブーム</h3>
                        <p class="discription-text">
                          最近『岩盤浴』にはまりました！<br>
                          岩盤浴は、新陳代謝を上げるだけではなく『美容』にも良いと言われています。<br>
                          さらには新陳代謝を上げるので、ダイエットにもいいと言われております。<br>
                          皆さんもご興味があれば是非、岩盤浴に入ってみてください。<br>
                          きっとクセになると思います♪<br>
                        </p>
                        </div>
                </div>
             </div>
        </section>


       <section id="sns">
         <div class="container3">
           <h2 class="heading3">
             ♨️〜その他〜♨️
           </h2>
           <p class="heading-text">
              登録したばかりですがSNSを始めました！<br>
              趣味を乗せたりスーパー銭湯の魅力をお伝えしていきたいので<br>
              興味のある方は是非見に来て下さい♪<br>
              また、みなさまに楽しくご利用していただける様に禁止事項を厳守の上ご利用をお願い致します。<br>
           </p>

           <div class="contact-group clearfix">

            <div class="left-content">
               <div class="comment-button">
                <%= link_to 'スーパー銭湯の共有をしましょう♪', new_blog_path, class: 'btn-border-comment' %>
               </div>

               <div class="precautions-button">
                <%= link_to '注意事項', precautions_blogs_path, class: 'btn-border-precautions' %>
               </div>
            </div>

             <div class="right-content">
              <div class="right-contact">
                <div class="SNS">
                <h3 class="discription-title">SNS</h3>

                  <%= link_to ("https://twitter.com/yosshi_ike1720") do %>
                    <span class="fa fa-twitter fa-x"aria-hidden="true"></span>
                  <% end %>


                  <%= link_to ("http://facebook.com/yosshi.freedom1720") do %>
                    <span class="fa fa-facebook fa-x"aria-hidden="true"></span>
                  <% end %>

                </div>
              </div>
             </div>
            </div>
       </section>
     </div>

</body>

app/views/blogs/edit.html.erb
<%= render 'menu' %>

<% if flash[:error_massages] %>
    <div class="alert alert-danger">
        <ul>
            <% flash[:error_massages].each do |massage| %>
                <li><<%= massage %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="b-edit_container">
    <div class="d-flex align-items-center">
        <div class="b-edit__comment">
            <h1>編 集</h1>
        </div>
          <div class="b-edit_comment_box">
                <%= link_to '温泉詳細', blog_path, class: 'btn-border-button' %>
          </div>
    </div>

        <%= form_for @blog do |f| %>

        <div class="b-blog__formbox">
             <div class="b-title_box">
                <%= f.label :title, '住所・温泉名' %>
                <%= f.text_field :title, class: 'form-control' %>
                <small id="title-tip" class="form-text text-muted">
                    住所・温泉名を入力してください
                </small>
            </div>
            <div class="b-content_box">
                <%= f.label :body, '投稿内容' %>
                <%= f.text_area :body, class: 'form-control', rows: 8 %>
                <small id="content-tip" class="form-text text-muted">
                    投稿内容を入力してください
                </small>
            </div>

            <div class="b-update_box">
                <%= f.submit '更新!', class: 'decorated-btn click-down' %>
            </div>
        </div>
</div>



<% end %>

app/views/blogs/index.html.erb
<%= render 'menu' %>

<div class="sakura2-container">

    <div class="d-flex align-items-center">
        <div class="b-index__comment">
          <h1>共有一覧</h1>
        </div>
        <div class="col-sm-2 col-md-offset-10">
          <%= link_to '戻る', new_blog_path, class: 'btn-border-back' %>
        </div>
    </div>

      <table class="table table-bordered border-primary table-sm blogs_table">
        <thead class="thead-dark">
          <tr>
            <th scope="col" style="width: 700px">住所・温泉名</th>
            <th scope="col">名前</th>
            <th scope="col">投稿日</th>
            <th scope="col">更新日時</th>
            <th scope="col">温泉詳細</th>
          </tr>
        </thead>

        <tbody>
            <% @blogs.each do |blog| %>
              <tr>
                  <td><%= blog.title %></td>
                <%= link_to users_path do %>
                  <td><%= blog.user.name %></td>
                <% end %>
                  <td><%= blog.created_at.to_s(:datetime_base) %></td>
                  <td><%= blog.updated_at.to_s(:datetime_base) %></td>
                  <td><%= link_to '温泉詳細', blog, id: "detail-" + blog.id.to_s, class: 'btn btn--momo btn--cubic btn--shadow', method: :get %></td>
                  <%# if blog.user_id == current_user.id %>
                    <td><%#= link_to "削除", blog, class: 'btn btn--danger btn--cubic btn--shadow', method: :delete, data: {confirm: "投稿記事を削除しますか？", cancel: "キャンセル", commit: "削除する", title: "削除の確認"} %></td>
                  <%# end %>
              </tr>
            <% end %>
        </tbody>
    </table>

  <%= paginate @blogs  %>
</div>

app/views/blogs/new.html.erb
<%= render 'menu' %>

<div class="b-new_container">

    <div class="d-flex align-items-center">
    	<div class="b-new__comment">
    		<h1>温泉の共有はこちら♪</h1>
    	</div>
      <div class="b-new_comment_box">
            <%= link_to '温泉共有一覧', blogs_path, class: 'btn-border-button' %>
      </div>
    </div>

        <%= render partial: 'form', locals: { blog: @blog } %>
</div>

app/views/blogs/precautions.html.erb
<%= render 'menu' %>

<div class="precaution-container">
	<div class="precaution-title">
		<h1>注意事項！</h1>
	</div>
	<div class="precaution-box">
		<h2>湯のここちでは気持ちよく利用して頂くため、以下を守りましょう！</h2>
		<br>
		<h3>
			1. 掲示板の趣旨と関係ない書き込み<br>
			2. 誹謗・中傷含む書き込み<br>
			3. 他人の権利を侵害するコンテンツの掲載<br>
			4. 他サイトやアプリの宣伝<br>
			5. アカウント売買目的の書き込み<br>
			6. 招待URLの書き込み<br>
		</h3>
		<br>
	</div>
</div>

app/views/blogs/show.html.erb
<%= render 'menu' %>

<div class="b-show_box">
	<div class="b-show__comment">
		<h1>温泉共有詳細</h1>
	</div>
		<div class="row-showbox">
			<div class="col-md-1"></div>
			<div class="col-md-5"></div>
			<div class="col-md-2"><%= link_to '共有一覧', blogs_path, class: 'btn-border-button' %></div>
			<% if @blog.user_id == current_user.id %>
		    <div class="col-md-2"><%= link_to '編集', edit_blog_path(@blog), class: 'btn-border-button' %></div>
		  <% end %>
		</div>
	</div>

		<% if flash[:notice] %>
			<div class="alert alert-primary"><%= flash[:notice] %></div>
		<% end %>

		<%= render @blog %>

		<div class="b-comment_list">
		  <div class="b-comment_listTitle"><h3>コメント<h3></div>
		  <%= render @blog.comments %>
		</div>

		<div id="user-modal" class="modal center-modal" tabindex="-1" role="dialog" aria-hidden="true"></div>

		<% if user_signed_in? %>
			<%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
		<% end %>
</div>