config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    # passwords: 'users/passwords'
  }

  devise_scope :users do
    get '/users', to: redirect("/users/sign_up")
  end



  resources :blogs do
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'see' => 'blogs#see'
      get 'look' => 'blogs#look'
      get 'saw' => 'blogs#saw'
      get 'watch' => 'blogs#watch'
      get 'seeing' => 'blogs#seeing'
      get 'looking' => 'blogs#looking'
      get 'check' => "blogs#check"
      get "try" => "blogs#try"
      get "gaze" => "blogs#gaze"
      get "info" => "blogs#info"
      get "precautions" => "blogs#precautions"
    end
  end

  resources :users do
    collection do
      get 'withdraw' => 'users#withdraw'
      get 'follows' => 'users#follows'
      get 'followers' => 'users#followers'
    end
    member do
      get 'show_modal' => 'users#show_modal'
    end
  end


  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:create]

  # resources :users, only: [:show, :edit, :update, :create, :destroy, :show_modal]

  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  patch 'users/update'
  get 'comments/create'
  get 'comments/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'blogs#browse'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get 'top' => 'homes#top'
  get 'browse' => 'blogs#browse'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog, optional: true

  validates :comment, presence: true, length: { maximum: 1000 }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
	    @comment = Comment.new(comment_params)
    	@comment.user_id = current_user.id
		if @comment.save
		    flash[:notice] = 'コメントを投稿しました！'
		    redirect_back(fallback_location: 'blog[:id]')
		else
		    redirect_to :rollback, flash: {
		    comment: @comment,
		    error_messages: @comment.errors.full_messages
		    }
	    end
	end

	def destroy
		comment = Comment.find(params[:id])
		comment.delete
		redirect_to comment.blog, flash: { notice: 'コメントが削除されました' }
	end

	private

	def comment_params
		params.require(:comment).permit(:comment, :reply_comment, :blog_id, :image)
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="b-show_container">
	<div class="b-comment__item">
	  <p><%= simple_format(comment.comment) %></p>
	  <div class="b-comment__bottomLine">

	<% if comment.user.profile_image.present? %>
		<%= link_to image_tag(comment.user.profile_image.to_s, :size =>'50x50'), show_modal_user_path(comment_id: comment.id), remote: true, class: "btn btn-lg, btn-primary" %>

		  <% if false %>
			  <%= link_to users_show_path do %>
			    <span><%= comment.user.name %></span>
			  <% end %>
		  <% end %>

		    <span><%= comment.created_at.to_s(:datetime_base) %></span>
		    <% if user_signed_in? && comment.user == current_user %>
		    <span><%= link_to "削除", comment, class: 'btn btn--red btn--radius', method: :delete, data: {confirm: "コメントを削除しますか？", cancel: "キャンセル", commit: "削除する", title: "削除の確認"} %></span>
		    <% end %>
		  </div>
		</div>
	<% else %>
		<%= link_to comment.user.name, show_modal_user_path(comment_id: comment.id), remote: true, class: "btn btn-lg, btn-primary" %>

		  <% if false %>
			  <%= link_to users_show_path do %>
			    <span><%= comment.user.name %></span>
			  <% end %>
		  <% end %>

		    <span><%= comment.created_at.to_s(:datetime_base) %></span>
		    <% if user_signed_in? && comment.user == current_user %>
		    <span><%= link_to "削除", comment, class: 'btn btn--red btn--radius', method: :delete, data: {confirm: "コメントを削除しますか？", cancel: "キャンセル", commit: "削除する", title: "削除の確認"} %></span>
		    <% end %>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<% if flash[:error_massages] %>
    <div class="alert alert-danger">
        <ul>
            <% flash[:error_massages].each do |massage| %>
                <li><<%= massage %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= render 'shared/error_messages' %>

<div class="b-comment__formBox">
	<p class="b-comment__formTitle">コメント記入</p>
	<%= form_for comment do |f| %>
	    <%= f.hidden_field :blog_id, :value => @blog.id %>
    	<div class="b-comment_box">
			<%= f.label :comment, 'コメント' %>
			<%= f.text_area :comment, class: 'form-control', rows: 4 %>
		</div>
        <div class="b-send_box">
            <%= f.submit '送信', class: 'decorated-btn click-down' %>
        </div>
	<% end %>
</div>