config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    # passwords: 'users/passwords'
  }

  devise_scope :users do
    get '/users', to: redirect("/users/sign_up")
  end



  resources :blogs do
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'see' => 'blogs#see'
      get 'look' => 'blogs#look'
      get 'saw' => 'blogs#saw'
      get 'watch' => 'blogs#watch'
      get 'seeing' => 'blogs#seeing'
      get 'looking' => 'blogs#looking'
      get 'check' => "blogs#check"
      get "try" => "blogs#try"
      get "gaze" => "blogs#gaze"
      get "info" => "blogs#info"
      get "precautions" => "blogs#precautions"
    end
  end

  resources :users do
    collection do
      get 'withdraw' => 'users#withdraw'
      get 'follows' => 'users#follows'
      get 'followers' => 'users#followers'
    end
    member do
      get 'show_modal' => 'users#show_modal'
    end
  end


  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:create]

  # resources :users, only: [:show, :edit, :update, :create, :destroy, :show_modal]

  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  patch 'users/update'
  get 'comments/create'
  get 'comments/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'blogs#browse'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get 'top' => 'homes#top'
  get 'browse' => 'blogs#browse'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tweets

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user, dependent: :destroy

  mount_uploader :profile_image, ProfileImageUploader

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 7 }



  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show_modal
    @comment = Comment.where(id: params[:comment_id]).first
    if @comment.present?
      respond_to :js
    else
      raise "id: #{params[:comment_id]}が見つかりませんでした。"
    end
  end

  def show
    @user = current_user
  end

  def index
  end

  def edit
  	@user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "「#{@user.name}」を変更しました！"
      redirect_to users_show_path
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if params[:user_profile_image_update_flg].present?
      @user.update_attribute(:profile_image, params[:user][:profile_image])
    else
      @user.update!(user_params)
    end
    redirect_to user_path(@user.id)


  end

  def withdraw
  end

  def follows
  end

  def followers
  end

  def set_variables
    @blog = Blog.find(params[:blog_id])
    @id_name = "#blog-link-#{@blog.id}"
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_image)
    end

    def user_profile_image_params
      params.require(:user).permit(:profile_image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% current_user.followings.each do |follow_user| %>
	<div class="follow-box">
		<div class="follow-image">
			<% if follow_user.profile_image.present? %>
				<%= image_tag follow_user.profile_image.to_s, :size =>'200x200' %>
			<% end %>
		</div>
		<h3 class="follow-name"><%= follow_user.name%></h3>
		<div class="follow-reset">
          <% if current_user.following?(follow_user) %>
            <%= form_for(current_user.relationships.find_by(follow_id: follow_user.id), html: { method: :delete }) do |f| %>
              <%= hidden_field_tag :follow_id, follow_user.id %>
              <%= f.submit 'フォロー解除', class: 'btn-border-reset' %>
            <% end %>
          <% else %>
            <%= form_for(current_user.relationships.build) do |f| %>
              <%= hidden_field_tag :follow_id, follow_user.id %>
              <%= f.submit 'フォロー', class: 'btn-border-follow' %>
            <% end %>
          <% end %>
		</div>
	</div>
<% end %>

app/views/users/_follower.html.erb
<% current_user.followers.each do |follow_user| %>
	<div class="follow-box">
		<div class="follow-image">
			<% if follow_user.profile_image.present? %>
				<%= image_tag follow_user.profile_image.to_s, :size =>'200x200' %>
			<% end %>
		</div>
		<h3 class="follow-name"><%= follow_user.name%></h3>
		<div class="follow-reset">
          <% if current_user.following?(follow_user) %>
            <%= form_for(current_user.relationships.find_by(follow_id: follow_user.id), html: { method: :delete }) do |f| %>
              <%= hidden_field_tag :follow_id, follow_user.id %>
              <%= f.submit 'フォロー解除', class: 'btn-border-reset' %>
            <% end %>
          <% else %>
            <%= form_for(current_user.relationships.build) do |f| %>
              <%= hidden_field_tag :follow_id, follow_user.id %>
              <%= f.submit 'フォロー', class: 'btn-border-follow' %>
            <% end %>
          <% end %>
		</div>
	</div>

<% end %>

app/views/users/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
  <div class="modal-show">
    <div class="modal-name">
      <h3>アカウント名: <%= @comment.user.name%> さんに</h3>
    </div>
    <h3>フォローしますか？</h3>
      <div class="follow-button">
        <% unless current_user == @comment.user %>
          <% if current_user.following?(@comment.user) %>
            <%= form_for(current_user.relationships.find_by(follow_id: @comment.user.id), html: { method: :delete }) do |f| %>
              <%= hidden_field_tag :follow_id, @comment.user.id %>
              <%= f.submit 'フォロー解除', class: 'btn-border-reset' %>
            <% end %>
          <% else %>
            <%= form_for(current_user.relationships.build) do |f| %>
              <%= hidden_field_tag :follow_id, @comment.user.id %>
              <%= f.submit 'フォロー', class: 'btn-border-follow' %>
            <% end %>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/_mypage.html.erb
<h3 class = "title-name"><%= link_to 'マイページ', users_show_path , class:"btn btn-primary" %></h3>

app/views/users/edit.html.erb
<%= render 'blogs/menu' %>

<div class="edit-container">
	<div class="user_edit">
		<h1>プロフィール編集</h1>
	</div>


	<div class="user_settings">
		<h1><%= @user.name %> さんのプロフィール画像設定</h1>
			<div class="user_settings_form">
				<%= form_for(@user) do |f| %>
				   <% if @user.profile_image.present? %>
				      <%= image_tag @user.profile_image.to_s, :size =>'200x200' %>
				   <% else %>
				      <%= image_tag "/assets/default.jpg" %>
				   <% end %>
				      <button type="button" class="btn btn-outline-secondary rounded-pill">
				         <%= f.file_field :profile_image, accept: 'image/jpeg,image/gif,image/png' %>
				      </button>
				      <input type="hidden" name="user_profile_image_update_flg" value="user_profile_image_update_flg" >
				　　<%= f.submit '更新する', class: 'btn btn-primary' %>
				<% end %>
			</div>
	</div>
</div>

app/views/users/followers.html.erb
<div class="follows">
    <h1>フォロワー</h1>
</div>

<div class="follows-box">
    <%= render 'follower' %>
</div>

app/views/users/follows.html.erb
<div class="follows">
    <h1>フォロー</h1>
</div>

<div class="follows-box">
    <%= render 'follow' %>
</div>

app/views/users/index.html.erb
#

app/views/users/new.js.erb
("#user-modal").html("<%= escape_javascript(render 'form') %>")
("#user-modal").modal("show")

app/views/users/show.html.erb
<%= render 'blogs/menu' %>
<div class="sakura_container">

	<div class="mypage">
		<h1>~ MY PAGE ~</h1>
	</div>


		<div class="row-box">
			<div class="col-md-5"></div>
			<div class="col-md-2"><%= link_to 'アカウント編集', edit_user_registration_path, class: 'btn-border-edit' %></div>

			<div class="col-md-2"><%= link_to 'プロフィール編集', edit_user_path, class: 'btn-border-edit' %></div>

			<div class="col-md-2"><%= link_to '退会', withdraw_users_path, class: 'btn-border-withdraw' %></div>
		</div>

		<div class="user_formbox">
			<div class="left_profile">
				<div class="user-face">
			   <% if @user.profile_image.present? %>
			      <%= image_tag @user.profile_image.to_s, :size =>'300x300' %>
			   <% else %>
			   	  <%= image_tag "img/no_image.jpg", :size =>'300x300' %>
			   <% end %>
				</div>
			</div>

			<div class="right_profile">
				<div class="profile_group1">
		            <h5 class="profile_name">アカウント名</h5>
		            <h3 class="user_name"><%= @user.name%></h3>
				</div>

				<div class="profile_group2">
		            <h5 class="profile_email">アドレス</h5>
		            <h3 class="user_email"><%= @user.email %></h3>
				</div>

				<div class="profile_group3">
				  <%= link_to 'フォロー', follows_users_path, class: "btn-border-follow" %>
				  <%= link_to 'フォロワー', followers_users_path, class: "btn-border-reset" %>
				</div>

			</div>

		</div>

</div>

app/views/users/show_modal.js.erb
// alert("test alert");

$("#user-modal").html("<%= escape_javascript(render 'form') %>")
$("#user-modal").modal("show")

app/views/users/withdraw.html.erb
<%= render "blogs/menu" %>

<div class="withdraw-container">
	<div class="withdraw-box">
	    <h2>退会しますか？</h2>
	</div>

	<div class="withdraw-text">
	    <h4>退会した場合、会員登録情報が「全て」削除され<br>
	  	サイトの閲覧ができなくなりますが、よろしいですか？</h4>
	</div>
	<div class="processing-box">
		<div class="col-md-3">
		</div>
				<div class="col-md-2"><%= link_to '戻る', user_path(current_user),class: "btn btn--cancel btn--border-solid"%></div>
				<div class="col-md-1">
				</div>
				<div class="col-md-2"><%= link_to '退会する', users_path(@user), method: :delete ,class: "btn btn--withdraw btn--border-solid",data: { confirm: '削除しますか？' }%></div>
	</div>
</div>