config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    # passwords: 'users/passwords'
  }

  devise_scope :users do
    get '/users', to: redirect("/users/sign_up")
  end



  resources :blogs do
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'see' => 'blogs#see'
      get 'look' => 'blogs#look'
      get 'saw' => 'blogs#saw'
      get 'watch' => 'blogs#watch'
      get 'seeing' => 'blogs#seeing'
      get 'looking' => 'blogs#looking'
      get 'check' => "blogs#check"
      get "try" => "blogs#try"
      get "gaze" => "blogs#gaze"
      get "info" => "blogs#info"
      get "precautions" => "blogs#precautions"
    end
  end

  resources :users do
    collection do
      get 'withdraw' => 'users#withdraw'
      get 'follows' => 'users#follows'
      get 'followers' => 'users#followers'
    end
    member do
      get 'show_modal' => 'users#show_modal'
    end
  end


  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:create]

  # resources :users, only: [:show, :edit, :update, :create, :destroy, :show_modal]

  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  patch 'users/update'
  get 'comments/create'
  get 'comments/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'blogs#browse'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get 'top' => 'homes#top'
  get 'browse' => 'blogs#browse'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <title>Onsen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
  <header>
        <a>
          <div class="nav-bar">
            <% if user_signed_in? %>
                  <i><%= link_to ' ホーム', browse_path, class: 'glyphicon glyphicon-home home' %></i>
                  <i><%= link_to ' お知らせ', info_blogs_path, class: 'glyphicon glyphicon-bell bell' %></i>
                  <i><%= link_to ' マイページ', user_path(current_user), class: 'glyphicon glyphicon-user user' %></i>
                  <i><%= link_to ' ログアウト', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></i>
            <% else %>
                  <i><%= link_to ' 新規登録', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></i>
                  <i><%= link_to ' ログイン', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></i>
                  <i><%= link_to ' ゲストログイン', homes_guest_sign_in_path, method: :post, class: 'glyphicon glyphicon-user user' %></i>
            <% end %>
          </div>
        </a>

    <%= link_to browse_path do %>
        <%= image_tag 'img/yunokokoti.png',class:"photo" %>
    <% end %>

  </header>
  <div class="main-contents">

      <div id="slidemenu">
        <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">

        </ul>
      </div>

      <%= yield %>
  <!--
      <script src="js/jquery.min.js"></script>
      <script src="js/skippr.min.js"></script>
      <script src="js/script.js"></script> -->


      <footer>
        <p class="">© Yunokokochi All Rights Reserved.</p>
      </footer>
  </div>
  </body>
</html>